preset: laravel
risky: true
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
  name: "*.php"
  not-name: "*.blade.php"
  contains: "thingy"
  not-contains: "other-thingy"
